# pyproject.toml
[tool.pytest.ini_options]
addopts = [
    "--screenshot", "only-on-failure",
    "--html=playwright-report/report.html",
    "--self-contained-html",
    "--junitxml=playwright-report/results.xml"
]